name: Update wiki
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v1
      env:
        SOURCE_REPO: "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git"
        SOURCE_BRANCH: "master"
        DESTINATION_REPO: "https://$GITHUB_ACTOR:${{secrets.WIKI_UPDATE_TOKEN}}@github.com/gohornet/hornet.wiki.git"
        DESTINATION_BRANCH: "master"
      with:
        args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH
